add yaml file to cd

diff --git a/.github/workflows/deploy-payments.yaml b/.github/workflows/deploy-payments.yaml
--- a/.github/workflows/deploy-payments.yaml
+++ b/.github/workflows/deploy-payments.yaml
@@ -1,13 +1,13 @@
-name: deploy-tickets
+name: deploy-payments
 
 on:
   push:
     branches:
       - master
     paths:
-      - 'tickets/**'
-      - 'infra/k8s/tickets-depl.yaml'
-      - '.github/workflows/deploy-tickets.yml'
+      - 'payments/**'
+      - 'infra/k8s/payments-depl.yaml'
+      - '.github/workflows/deploy-payments.yml'
 
 env:
   AWS_REGION: us-east-1
@@ -22,8 +22,9 @@ jobs:
 
       - name: Check Directory & Manifest
         run: |
-          if [ ! -d "./auth" ]; then echo "Directory ./auth not found"; exit 1; fi
-          if [ ! -f "./infra/k8s/auth-deployment.yaml" ]; then echo "Manifest file not found"; exit 1; fi
+          if [ ! -d "./payments" ]; then echo "Directory ./payments not found"; exit 1; fi
+          if [ ! -f "./infra/k8s/payments-deployment.yaml" ]; then echo "Manifest file not found"; exit 1; fi
+          if [ ! -f "./infra/k8s/ingress-srv.yaml" ]; then echo "Manifest ingress-srv.yaml not found"; exit 1; fi
 
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v4
@@ -44,7 +45,7 @@ jobs:
       - name: Build & Push Docker Image
         uses: docker/build-push-action@v6
         with:
-          context: ./tickets
+          context: ./payments
           push: true
           tags: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/auth:${{ github.sha }}
           cache-from: type=gha
@@ -68,7 +69,7 @@ jobs:
 
       - name: Update manifests with new image
         run: |
-          yq eval ".spec.template.spec.containers[0].image = env(IMAGE)" -i infra/k8s/tickets-depl.yaml
+          yq eval ".spec.template.spec.containers[0].image = env(IMAGE)" -i infra/k8s/payments-depl.yaml
 
       - name: Validate Kubernetes Manifests
         run: kubectl apply -f infra/k8s --dry-run=client
@@ -77,4 +78,4 @@ jobs:
         run: kubectl apply -f infra/k8s
 
       - name: Verify rollout
-        run: kubectl rollout status deployment/tickets-deployment --timeout=60s
+        run: kubectl rollout status deployment/payments-depl --timeout=60s
diff --git a/.github/workflows/deploy-tickets.yaml b/.github/workflows/deploy-tickets.yaml
--- a/.github/workflows/deploy-tickets.yaml
+++ b/.github/workflows/deploy-tickets.yaml
@@ -1,13 +1,13 @@
-name: deploy-auth
+name: deploy-tickets
 
 on:
   push:
     branches:
       - master
     paths:
-      - 'auth/**'
-      - 'infra/k8s/auth-depl.yaml'
-      - '.github/workflows/deploy-auth.yml'
+      - 'tickets/**'
+      - 'infra/k8s/tickets-depl.yaml'
+      - '.github/workflows/deploy-tickets.yml'
 
 env:
   AWS_REGION: us-east-1
@@ -22,8 +22,8 @@ jobs:
 
       - name: Check Directory & Manifest
         run: |
-          if [ ! -d "./auth" ]; then echo "Directory ./auth not found"; exit 1; fi
-          if [ ! -f "./infra/k8s/auth-deployment.yaml" ]; then echo "Manifest file not found"; exit 1; fi
+          if [ ! -d "./tickets" ]; then echo "Directory ./tickets not found"; exit 1; fi
+          if [ ! -f "./infra/k8s/tickets-deployment.yaml" ]; then echo "Manifest file not found"; exit 1; fi
           if [ ! -f "./infra/k8s/ingress-srv.yaml" ]; then echo "Manifest ingress-srv.yaml not found"; exit 1; fi
 
       - name: Configure AWS credentials
@@ -45,7 +45,7 @@ jobs:
       - name: Build & Push Docker Image
         uses: docker/build-push-action@v6
         with:
-          context: ./auth
+          context: ./tickets
           push: true
           tags: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/auth:${{ github.sha }}
           cache-from: type=gha
@@ -69,7 +69,7 @@ jobs:
 
       - name: Update manifests with new image
         run: |
-          yq eval ".spec.template.spec.containers[0].image = env(IMAGE)" -i infra/k8s/auth-depl.yaml
+          yq eval ".spec.template.spec.containers[0].image = env(IMAGE)" -i infra/k8s/tickets-depl.yaml
 
       - name: Validate Kubernetes Manifests
         run: kubectl apply -f infra/k8s --dry-run=client
@@ -78,4 +78,4 @@ jobs:
         run: kubectl apply -f infra/k8s
 
       - name: Verify rollout
-        run: kubectl rollout status deployment/auth-depl --timeout=60s
+        run: kubectl rollout status deployment/tickets-depl --timeout=60s
